spring:
  application:
    name: quizesMongo
  data:
    mongodb:
      uri: mongodb://localhost:27018/users
  profiles:
    active: dev

  config:
    import: configserver:http://localhost:9094
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



server:
  port: 9092




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



