spring:
  application:
    name: quizesMongo
  data:
    mongodb:
      uri: mongodb://localhost:27018/users
  profiles:
    active: dev

  config:
    import: configserver:http://localhost:9094
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      web:
        path: "/function"
      definition: acknowledged
    stream:
      bindings:
        quizCreatedBinding-out-0:
          destination: quiz-created
          group: ${spring.application.name}
        acknowledged-in-0:
          destination: quiz-acknowledged
          group: ${spring.application.name}


server:
  port: 9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


#Resilience4j configuration
#Defines the number of calls the CB should keep track of to calculate the failure percentage
resilience4j:
  circuitbreaker:
    configs:
      defaults:
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

