spring:
  application:
    name: question
  data:
    mongodb:
      uri: mongodb://localhost:27018/question


  config:
    import: configserver:http://localhost:9094
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      web:
        path: "/function"

server:
  port: 9095

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


