spring:
  application:
    name: question
  data:
    mongodb:
      uri: mongodb://localhost:27018/question

  config:
    import: configserver:http://localhost:9094
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  cloud:
    function:
      web:
        path: "/function"
      definition: getQuizBinding
    stream:

      bindings:
        getQuizBinding-in-0:
          destination: quiz-created
          group: ${spring.application.name}
        getQuizBinding-out-0:
          destination: quiz-acknowledged
          group: ${spring.application.name}
      kafka:
        binder:
          brokers: localhost:9092
      binders:
        kafkaBinder:
          type: kafka
  ai:
    openai:
      api-key: ${API_KEY}



server:
  port: 9095

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


